// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrb_INcsnFZlP-D2wXJOSXVAofxLiywmI',
    appId: '1:184769929378:web:f9d5cf3c47403b70d637fb',
    messagingSenderId: '184769929378',
    projectId: 'pralay-58be9',
    authDomain: 'pralay-58be9.firebaseapp.com',
    storageBucket: 'pralay-58be9.firebasestorage.app',
    measurementId: 'G-DPYKPHRQ44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJlzMo4zUyvnN2imGfqmhgdbNpVD0mHw',
    appId: '1:184769929378:android:cdab9ebd2d376024d637fb',
    messagingSenderId: '184769929378',
    projectId: 'pralay-58be9',
    storageBucket: 'pralay-58be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt9YzjC5KpatNeGmoxnihVjbuxUNnqjcI',
    appId: '1:184769929378:ios:dac4f5e33667f7b2d637fb',
    messagingSenderId: '184769929378',
    projectId: 'pralay-58be9',
    storageBucket: 'pralay-58be9.firebasestorage.app',
    iosBundleId: 'com.example.splitAppUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt9YzjC5KpatNeGmoxnihVjbuxUNnqjcI',
    appId: '1:184769929378:ios:dac4f5e33667f7b2d637fb',
    messagingSenderId: '184769929378',
    projectId: 'pralay-58be9',
    storageBucket: 'pralay-58be9.firebasestorage.app',
    iosBundleId: 'com.example.splitAppUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrb_INcsnFZlP-D2wXJOSXVAofxLiywmI',
    appId: '1:184769929378:web:aff6ff038f1d4dced637fb',
    messagingSenderId: '184769929378',
    projectId: 'pralay-58be9',
    authDomain: 'pralay-58be9.firebaseapp.com',
    storageBucket: 'pralay-58be9.firebasestorage.app',
    measurementId: 'G-3JTCYZ44XR',
  );
}
